name: Angular CI/CD

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js 24
        uses: actions/setup-node@v5
        with:
          node-version: '24'
          cache: 'npm'
          cache-dependency-path: 'myHomeTown/package-lock.json'

      - name: Install dependencies
        run: npm ci
        working-directory: ./myHomeTown

      - name: Build Angular app
        run: npm run build -- --configuration=production
        working-directory: ./myHomeTown

      - name: Run tests
        run: npm run test -- --watch=false --browsers=ChromeHeadless
        working-directory: ./myHomeTown